name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
      - name: Test Docker build
        run: docker build . --file Dockerfile
      - name: Test action
        uses: ./
        with:
          theme: jsonresume-theme-even
          input_file: resume.json
          output_file: resume.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: resume.html
          path: resume.html
